name: publish

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: './publishing-package' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '3.1.103' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ env.DOTNET_VERSION}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies and restore
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH}} --no-build
      
    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
